language: generic
services:
- docker
before_install:
- cd && mkdir -p build/ddulic/resume/output
install:
- docker run -v $HOME/build/ddulic/resume:/resume there4/markdown-resume md2resume pdf -t readable ddulic.md output/
- cd build/ddulic/resume && ./generate-resume-page.sh ddulic.md index.md && ./push-to-hexo-website.sh
